### PR TITLE
python 3.8

### PR DESCRIPTION
**Pull request by domdinicola**

### CODE REVIEW

**Comment by domdinicola** [comment]
@reinbach any idea of why this fails?

**Comment by reinbach** [comment]
@domdinicola Make sure that `m.complete` is actually returning an object. Looks like `v.transition` does, I'm not 100% sure about `m.complete` . Or maybe update that test assertion to be more specific.

e.g. 
```
m.complete
m.refresh_from_db()
assert m.status == v.transition.status
```

**Comment by reinbach** [comment]
@domdinicola The issue was due to the way Python 3.8 now compares methods. The comparison fails now in 3.8 if the methods are not of the same instance.
See https://stackoverflow.com/questions/58822724/comparing-object-methods-leads-to-different-results-in-3-8 for a good explanation

**Comment by domdinicola** [comment]
@reinbach  how do you feel about django-fsm/django-fsa?

**Comment by reinbach** [comment]
> @reinbach how do you feel about django-fsm/django-fsa?

@domdinicola I think we need to go with django-fsa as it is what is being maintained and works with 3.8

**Pull request merged**
